// <auto-generated />
using System;
using MeAgendaAe.Dominio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeAgendaAe.Dominio.Migrations
{
    [DbContext(typeof(MeAgendaAeContext))]
    [Migration("20220904003431_UpdatingColunms")]
    partial class UpdatingColunms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbAgendamentos", b =>
                {
                    b.Property<long>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaSemana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint");

                    b.Property<long>("IdStatusAgendamento")
                        .HasColumnType("bigint");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdStatusAgendamento");

                    b.ToTable("TbAgendamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbCidades", b =>
                {
                    b.Property<long>("IdCidades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCidades");

                    b.ToTable("TbCidades");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbCliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdCidade")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEstado")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QtdVisitas")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("TbCliente");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbConfiguracoes", b =>
                {
                    b.Property<int>("IdConfiguracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.HasKey("IdConfiguracao");

                    b.ToTable("TbConfiguracoes");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbEmpresas", b =>
                {
                    b.Property<long>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<long>("IdCidade")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEstado")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdEstado");

                    b.ToTable("TbEmpresas");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbEstados", b =>
                {
                    b.Property<long>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstado");

                    b.ToTable("TbEstados");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbFormasPagamentos", b =>
                {
                    b.Property<int>("IdFormasPagamentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoFormaPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormasPagamentos");

                    b.ToTable("TbFormasPagamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbPagamentos", b =>
                {
                    b.Property<long>("IdPagamentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdFormaPagamento")
                        .HasColumnType("int");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPagamentos");

                    b.HasIndex("IdFormaPagamento");

                    b.ToTable("TbPagamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbStatusAgendamentos", b =>
                {
                    b.Property<long>("IdStatusAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStatusAgendamento");

                    b.ToTable("TbStatusAgendamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbUsuarios", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TbCidadesIdCidades")
                        .HasColumnType("bigint");

                    b.Property<long?>("TbEstadosIdEstado")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("TbCidadesIdCidades");

                    b.HasIndex("TbEstadosIdEstado");

                    b.ToTable("TbUsuarios");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbAgendamentos", b =>
                {
                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbCliente", "TbCliente")
                        .WithMany("TbAgendamentos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbEmpresas", "TbEmpresas")
                        .WithMany("TbAgendamentos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbStatusAgendamentos", "TbStatusAgendamentos")
                        .WithMany("TbAgendamentos")
                        .HasForeignKey("IdStatusAgendamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TbCliente");

                    b.Navigation("TbEmpresas");

                    b.Navigation("TbStatusAgendamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbCliente", b =>
                {
                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbCidades", "TbCidades")
                        .WithMany("TbCliente")
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbEstados", "TbEstados")
                        .WithMany("TbCliente")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbUsuarios", "TbUsuarios")
                        .WithOne("TbCliente")
                        .HasForeignKey("MeAgendaAe.CamadaDados.Tabelas.TbCliente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TbCidades");

                    b.Navigation("TbEstados");

                    b.Navigation("TbUsuarios");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbEmpresas", b =>
                {
                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbCidades", "TbCidades")
                        .WithMany("TbEmpresas")
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbEstados", "TbEstados")
                        .WithMany("TbEmpresas")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TbCidades");

                    b.Navigation("TbEstados");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbPagamentos", b =>
                {
                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbFormasPagamentos", "TbFormasPagamentos")
                        .WithMany("TbPagamentos")
                        .HasForeignKey("IdFormaPagamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TbFormasPagamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbUsuarios", b =>
                {
                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbCidades", null)
                        .WithMany("TbUsuarios")
                        .HasForeignKey("TbCidadesIdCidades")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeAgendaAe.CamadaDados.Tabelas.TbEstados", null)
                        .WithMany("TbUsuarios")
                        .HasForeignKey("TbEstadosIdEstado")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbCidades", b =>
                {
                    b.Navigation("TbCliente");

                    b.Navigation("TbEmpresas");

                    b.Navigation("TbUsuarios");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbCliente", b =>
                {
                    b.Navigation("TbAgendamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbEmpresas", b =>
                {
                    b.Navigation("TbAgendamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbEstados", b =>
                {
                    b.Navigation("TbCliente");

                    b.Navigation("TbEmpresas");

                    b.Navigation("TbUsuarios");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbFormasPagamentos", b =>
                {
                    b.Navigation("TbPagamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbStatusAgendamentos", b =>
                {
                    b.Navigation("TbAgendamentos");
                });

            modelBuilder.Entity("MeAgendaAe.CamadaDados.Tabelas.TbUsuarios", b =>
                {
                    b.Navigation("TbCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
